#!/bin/bash
BASEDIR=$(pwd -P)
chmod +x oclauncher
chmod +x vpncredential
sudo apt-get install git jq \
    build-essential gettext autoconf automake libproxy-dev \
    libxml2-dev libtool vpnc-scripts pkg-config \
    libgnutls28-dev
cd /tmp
git clone https://github.com/dlenski/openconnect.git
cd openconnect
./autogen.sh
./configure
make
sudo make install && sudo ldconfig
echo "openconnect successfully installed!"
cd $BASEDIR
INSTALDIR=~/.local/bin
cp "vpncredential" "$INSTALDIR"
cp "hipreport.sh" "$INSTALDIR"
cp "oclauncher" "$INSTALDIR"
cd $INSTALDIR
sudo $INSTALDIR/oclauncher
