#!/bin/bash
BASEDIR=$(pwd -P)
chmod +x ovlauncher
chmod +x ovcredential
sudo apt-get install git jq \
    build-essential gettext autoconf automake libproxy-dev \
    libxml2-dev libtool vpnc-scripts pkg-config \
    libgnutls28-dev
cd /tmp
git clone https://github.com/dlenski/openconnect.git
cd openconnect
./autogen.sh
./configure
make
sudo make install && sudo ldconfig
echo "openconnect successfully installed!"
cd $BASEDIR
INSTALDIR=~/.local/bin
cp "ovcredential" "$INSTALDIR"
cp "ovreport" "$INSTALDIR"
cp "ovlauncher" "$INSTALDIR"
cd $INSTALDIR
sudo $INSTALDIR/ovlauncher
