#!/bin/bash
BASEDIR=$(pwd -P)
chmod +x ovlauncher
chmod +x ovcredential
sudo apt install openconnect jq oathtool
echo "openconnect successfully installed!"
cd $BASEDIR
INSTALDIR=/usr/local/bin
cp "ovcredential" "$INSTALDIR"
cp "ovreport" "$INSTALDIR"
cp "ovlauncher" "$INSTALDIR"
cp "ovstealth.sh" "$INSTALDIR"
cd $INSTALDIR
sudo $INSTALDIR/ovlauncher
