#!/bin/bash
if [[ $UID != 0 ]]; then
    echo "Please run this executable with sudo:"
    eval "sudo $0 $*"
    exit 1
fi
GREEN='\033[0;32m'  # ANSI escape code for green text
NC='\033[0m'        # ANSI escape code to reset text color
banner="
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
OPENCONNECT VPN CONNECTION
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
"

clear
echo "$banner"
BASEDIR=$(dirname "$0")
FILE=$BASEDIR/.ocvpn
if [ -f $FILE ] ; then

  json=$(echo $(cat $FILE | base64 --decode))
  url=$(echo $json | jq '.url' | tr -d \")
  user=$(echo $json | jq '.user' | tr -d \")
  pass=$(echo $json | jq '.pass' | tr -d \")
  echo Please enter OTP token
  read token
  echo $pass$token | sudo openconnect --protocol=gp $url --user=$user --passwd-on-stdin --csd-wrapper="$BASEDIR/ovreport" --no-dtls
else
  $BASEDIR/ovcredential
  $0
fi

echo -n ""
for i in {15..1}; do
    printf "\r reconnecting in ${GREEN}%d${NC} seconds" "$i"
    sleep 1  # Optional: Add a sleep to slow down the loop for better visibility
done
echo  # Add a newline to move to the next line after the loop completes

./ovlauncher
